syntax = "proto3";

package {{ cookiecutter.service_package_name }};

option go_package = "{{ cookiecutter.go_module }}/api/{{ cookiecutter.service_package_name }}";

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "validate/validate.proto";

service {{ cookiecutter.__service_name_title }} {
  // Object
  rpc GetObject(GetObjectRequest) returns (GetObjectResponse) {
    option (google.api.http) = {
      get: "{{ cookiecutter.api_path_prefix }}/object/get"
    };
  }

  rpc ListObjects(ListObjectsRequest) returns (ListObjectsResponse) {
    option (google.api.http) = {
      get: "{{ cookiecutter.api_path_prefix }}/object/list"
    };
  }

  rpc CreateObject(CreateObjectRequest) returns (CreateObjectResponse) {
    option (google.api.http) = {
      post: "{{ cookiecutter.api_path_prefix }}/object/create"
      body: "*"
    };
  }

  rpc UpdateObject(UpdateObjectRequest) returns (UpdateObjectResponse) {
    option (google.api.http) = {
      post: "{{ cookiecutter.api_path_prefix }}/object/update"
      body: "*"
    };
  }

  rpc DeleteObject(DeleteObjectRequest) returns (DeleteObjectResponse) {
    option (google.api.http) = {
      post: "{{ cookiecutter.api_path_prefix }}/object/delete"
      body: "*"
    };
  }
}

// Object

enum ObjectStatus {
  OBJECT_STATUS_ACTIVE = 0;
  OBJECT_STATUS_DELETED = 1;
}

message Object {
  string id = 1;
  string name = 2 [(validate.rules).string.max_len = 100];
  string description = 3 [(validate.rules).string.max_len = 1000];
  int32 status = 4 [(validate.rules).int32.gte = 0]; // ObjectStatus
  google.protobuf.Timestamp create_time = 5;
  google.protobuf.Timestamp update_time = 6;
}

message GetObjectRequest {
  string id = 1 [(validate.rules).string.min_len = 1];
}

message GetObjectResponse {
  Object object = 1;
}

message ListObjectsRequest {
  int32 offset = 1 [(validate.rules).int32.gte = 0];
  int32 limit = 2 [(validate.rules).int32.gte = 0, (validate.rules).int32.lte = 100];
}

message ListObjectsResponse {
  repeated Object objects = 1;
  int32 total = 2;
}

message CreateObjectRequest {
  string name = 1 [(validate.rules).string = {min_len: 1, max_len: 100}];
  string description = 2 [(validate.rules).string.max_len = 1000];
}

message CreateObjectResponse {
  Object object = 1;
}

message UpdateObjectRequest {
  string id = 1 [(validate.rules).string.min_len = 1];
  string description = 2 [(validate.rules).string.max_len = 1000];
}

message UpdateObjectResponse {
  Object object = 1;
}

message DeleteObjectRequest {
  string id = 1 [(validate.rules).string.min_len = 1];
}

message DeleteObjectResponse {}
