debug: true
beautify_log: true
app:
  name: {{ cookiecutter.app_name }}
  observable:
    endpoints:
      http: ":8080"
    modules:
      - pprof
      - metrics
      - swagger
      - channelz
      - grpcui
  services:
    - name: {{ cookiecutter.service_name }}
      endpoints:
        grpc: ":9000"
        http: ":8000"
      middlewares:
        - recovery
        - metrics
        - context_logger
        - log_request
        - name: cors
          allow_origins: ["*"]
          allow_headers: ["*"]
          expose_headers: ["*"]
          max_age: 86400
        - request_validation
  databases:
    - name: {{ cookiecutter.service_name }}
      type: postgres
      database: {{ cookiecutter.service_name }}_db
      user: {{ cookiecutter.service_name }}
      password: password
      masters: ["127.0.0.1:5432"]
      slaves: []
  id_generator:
    service_id: 1
    key: "{{ uuid4()|replace('-', '') }}"
